feat(sidecar-terminator): added initial helm chart
StatCan/charts pull request #217
Opened 2022-03-08 14:59 UTC by mohameddahrouj

Adding Helm chart to be able to easily configure [kubernetes-sidecar-terminator](https://github.com/zachomedia/kubernetes-sidecar-terminator) on each cluster.

Ref: https://jirab.statcan.ca/browse/CN-742

2022-03-08 16:48 UTC, justbert requested changes
Have a couple of comments.

Can you please also use the **Common Labels** template in `_helpers.tpl` to set the labels on all the resources instead of using `app.kubernetes.io/name: {{ include "sidecar-terminator.fullname" . }}`?

2022-03-08 16:48 UTC, justbert commented on stable/sidecar-terminator/Chart.yaml
> +icon: https://istio.io/latest/favicons/android-192x192.png
Hmmm... Where did this come from? Charts should be started from a `helm create`. :)

2022-03-08 16:48 UTC, justbert commented on stable/sidecar-terminator/values.yaml
> +affinity: {}
I don't see these in the Deployment's configurations, are they used?

2022-03-08 16:51 UTC, justbert commented on stable/sidecar-terminator/values.yaml
> +affinity: {}
Instead of removing them, can you please update the Deployment to allow them to be specified? It can be important in certain scenarios.

2022-03-08 16:53 UTC, mohameddahrouj commented on stable/sidecar-terminator/Chart.yaml
> +icon: https://istio.io/latest/favicons/android-192x192.png
This chart was originally initiated with `helm create`! I just Googled an istio icon and used it lol to avoid the warning when linting :p

2022-03-08 16:54 UTC, mohameddahrouj commented on stable/sidecar-terminator/values.yaml
> +affinity: {}
Will do

2022-03-08 16:58 UTC, justbert commented on stable/sidecar-terminator/Chart.yaml
> +icon: https://istio.io/latest/favicons/android-192x192.png
Oh gotcha! This sidecar-terminator isn't strictly for Istio and we shouldn't be using the Istio icon for our own applications as described in https://istio.io/latest/about/media-resources/.

2022-03-08 18:10 UTC, mohameddahrouj commented on stable/sidecar-terminator/Chart.yaml
> +icon: https://istio.io/latest/favicons/android-192x192.png
Thanks for sharing that!

2022-03-08 19:33 UTC, justbert requested changes
Can you remove the namespace field from the resources. Added a quick reason why in the `values.yaml` file.

2022-03-09 12:53 UTC, justbert commented on stable/sidecar-terminator/values.yaml
> +namespace: kube-system
Hmmm... That's a good question! It would be really dependent. If you were simply using Helm as a templating engine via the `helm template` command for your chart, that may be a time where you'd want to put in the namespace directly. If you look at some of my old charts you'll see that I was adding the namespace via the `.Release.Namespace` object, but I'm moving to just not using it anymore since it's not needed (and I'm lazy!). 

Especially with the post-renderers nowadays, you're not usually sure how someone will use the chart so the widely used standard is just not to add the namespace field.

https://helm.sh/docs/topics/advanced/#post-rendering

2022-03-09 13:37 UTC, justbert requested changes

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/deployment.yaml
> +  namespace: {{ .Values.namespace }}
```suggestion
```

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/role.yaml
> +  namespace: {{ .Values.namespace }}
```suggestion
```

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/rolebinding.yaml
> +  namespace: {{ .Values.namespace }}
```suggestion
```

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/serviceaccount.yaml
> +  namespace: {{ .Values.namespace }}
```suggestion
```

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/clusterrolebinding.yaml
> +  namespace: {{ .Values.namespace }}
Oh and this is where you would put a 
```suggestion
  namespace: {{ .Release.Namespace }}
```

2022-03-09 13:37 UTC, justbert commented on stable/sidecar-terminator/templates/rolebinding.yaml
> +  namespace: {{ .Values.namespace }}
```suggestion
  namespace: {{ .Release.Namespace }}
```

2022-03-09 13:37 UTC, mohameddahrouj commented on stable/sidecar-terminator/values.yaml
> +namespace: kube-system
Ah ok. That makes sense. Thanks Justin, I'll remove them in that case!

2022-03-09 15:23 UTC, justbert commented on stable/sidecar-terminator/templates/deployment.yaml
> +  replicas: 1
One last thing! 

Can you make this configurable? The `sidecar-terminator` can be horizontally scaled and it uses lease-locks to determine the primary!

2022-03-09 15:36 UTC, justbert approved these changes

2022-03-09 15:36 UTC, merged