Create the Azure Client Secret to be used in ckanext-util
StatCan/charts pull request #26
Opened 2021-06-24 02:15 UTC by Locutus66

- Added to values.yml and ckan.yml (correctly, I hope...)

2021-06-24 02:39 UTC, blairdrummond commented
@sylus I have a PR into his repo with suggested changes. I'll test in kind before giving a thumbs up but thats a tomorrow thing

2021-06-25 11:55 UTC, Locutus66 commented
Any movement on this? The latest image that contains our extensions is expecting this value to be in place for the pod to start properly.

2021-06-25 12:47 UTC, blairdrummond commented
Hi @Locutus66 , did you see

https://github.com/Locutus66/charts/pull/1

2021-06-25 12:49 UTC, blairdrummond requested changes

2021-06-25 12:49 UTC, blairdrummond commented on stable/ckan/templates/deploy/ckan.yaml
> +                name: { { include "ckan.fullname" . } }-util
You added this value to the secret `{{ include "ckan.fullname" . }}`, but here you call it `{ { include "ckan.fullname" . } }-util`. So this will fail. Also there shouldn't be spaces between the `{ {` or `} }`

2021-06-25 12:49 UTC, blairdrummond commented on stable/ckan/templates/secret/ckan.yaml
> +  azureClientSecretUtil: {{ .Values.ckan.azureClientSecretUtil }}
I would move this into a separate secret. See my PR

2021-06-25 13:22 UTC, blairdrummond commented
Need to also bump the chart version

https://github.com/StatCan/charts/blob/44e06331d2b17b4133fbb68ea5c87ee1e7c57ed5/stable/ckan/Chart.yaml#L4

2021-06-25 13:26 UTC, Locutus66 commented
Bumped up version just now.

2021-06-25 13:43 UTC, blairdrummond approved these changes
I get a client authentication error since I don't have the value for the azure secret, but otherwise seems to deploy fine.

[test-ckan.zip](https://github.com/StatCan/charts/files/6716522/test-ckan.zip)

2021-06-25 13:45 UTC, blairdrummond commented
@sylus seems to be working minus the fact that there's a client error since I can't test with the azure id he's using. I think this is probably good to merge but as-per discussion with @Locutus66 any future update he'll need to use kind to test the chart in advance locally to confirm all is working.

2021-06-25 13:45 UTC, blairdrummond commented
(Hit the wrong button)

2021-06-25 14:09 UTC, sylus approved these changes

2021-06-25 14:09 UTC, merged