patch: Fdi dotstatsuite logging config
StatCan/charts pull request #281
Opened 2022-08-18 18:10 UTC by GoodTown

added log4net config map for Authz and Transfer services.

2022-08-18 18:11 UTC, GoodTown commented
take the fdi-dotstatsuite-logging-config changes in conflicts

2022-08-19 18:26 UTC, MichaelPatsula requested changes

2022-08-19 18:26 UTC, MichaelPatsula commented on stable/fdi-dotstatsuite/values.yaml
> +transferlog4net-config:
I think the dash needs to be removed from the **transferlog4net-config** & **authzlog4net-config** variable names. In the rest of the helm chart this variable is referenced without the dash (.Values.transferlog4netconfig & authzlog4netconfig). The [best practice](https://helm.sh/docs/chart_best_practices/values/#naming-conventions) is to use camel case to separate words.

2022-08-19 18:26 UTC, MichaelPatsula commented on stable/fdi-dotstatsuite/templates/deploy/transfer.yaml
> +              value: {{.Values.transfer.dataImportTimeOutInMinutes}}
I recommend adding a space before and after the two curly braces to keep the formatting consistent. 

example:
 {{ .Values.transfer.dataImportTimeOutInMinutes }} instead of  {{.Values.transfer.dataImportTimeOutInMinutes}}

2022-08-19 18:26 UTC, MichaelPatsula commented on stable/fdi-dotstatsuite/templates/deploy/authz.yaml
> +              subPath: log4net.config
Is the subPath here necessary? Here is the official documentation for it https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath.

2022-08-22 13:53 UTC, sylus commented
We can merge once @MichaelPatsula comments have been addressed :)

2022-08-24 19:25 UTC, GoodTown commented on stable/fdi-dotstatsuite/values.yaml
> +transferlog4net-config:
Changes the variables to camel casing

2022-08-24 19:25 UTC, GoodTown commented on stable/fdi-dotstatsuite/templates/deploy/transfer.yaml
> +              value: {{.Values.transfer.dataImportTimeOutInMinutes}}
added spaces after injected values

2022-08-25 13:00 UTC, MichaelPatsula approved these changes
LGTM!

2022-09-01 15:46 UTC, GoodTown commented
@MichaelPatsula can these changes be merged into master

2022-09-01 18:14 UTC, merged