Dynamic secret configuration added to fluentd configmap
StatCan/charts pull request #385
Opened 2023-02-09 14:19 UTC by vashisthk1

-vars added in values file 
-secretref key
-dynamic password
-dynamic ingress points

2023-02-09 14:31 UTC, wg102 requested changes
Hello, I did a quick review. If you could clarify the concerns about the password.

2023-02-09 14:31 UTC, wg102 commented on stable/fdi-eck/templates/deploy/elastic.yaml
> +
Not strictly necessary but please clean up the files to format. One empty line is usual standard

2023-02-09 14:31 UTC, wg102 commented on stable/fdi-eck/values_minikube.yaml
> +  password: "elasticPassword"
Hardcoded password?

2023-02-09 14:32 UTC, rohank07 commented on stable/fdi-eck/values.yaml
> +  elasticSearchPassword: "k8s-cancentral-01-development"
Open-text password - use K8s secret

2023-02-09 18:20 UTC, vashisthk1 commented on stable/fdi-eck/values.yaml
> +  elasticSearchPassword: "k8s-cancentral-01-development"
Removed the passwords, was not working.

2023-02-09 18:21 UTC, vashisthk1 commented on stable/fdi-eck/values_minikube.yaml
> +  password: "elasticPassword"
removed, unable to use

2023-02-09 18:33 UTC, wg102 approved these changes

2023-02-23 18:30 UTC, vashisthk1 commented
Hi, please merge the request now. Fixed the bug. 

Thank you for your help!

2023-02-23 19:42 UTC, Jose-Matsuda approved these changes

2023-02-23 19:43 UTC, Jose-Matsuda commented
You can Squash and Merge at your convenience
![image](https://user-images.githubusercontent.com/23174198/221013368-21c8fc0b-7681-4b49-a7e9-04c6168ceeed.png)

2023-03-02 14:39 UTC, vashisthk1 commented
> You can Squash and Merge at your convenience ![image](https://user-images.githubusercontent.com/23174198/221013368-21c8fc0b-7681-4b49-a7e9-04c6168ceeed.png)

Hi, 

I cannot see this option. Is it a permissions issue?

If possible can you please squash and merge?

Thanks,
Kartik

2023-03-02 14:46 UTC, merged